Error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])
needed to https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1108